### Request 1: Create a course (Correct)
POST http://localhost:3000/courses HTTP/1.1
content-type: application/json

{
    "name": "Augusta National",
    "location": "Augusta, Georgia",
    "par": 72,
    "distance": 7445,
    "slope": 140    
}

### Request 2: Retrieve all
GET http://localhost:3000/courses HTTP/1.1

### Request 3: Create a course (Incorrect)
POST http://localhost:3000/courses HTTP/1.1
content-type: application/json

{
    "name": "Augusta National",
    "location": "",
    "par": 72,
    "distance": 7445,
    "slope": 140  
}

### Request 4: Delete a course
@COURSE_ID = 697d91408b715342be342b3e

DELETE http://localhost:3000/courses/{{COURSE_ID}} HTTP/1.1

### Request 4: Get course by ID
@COURSE_ID_REAL = 697e7a1624d6aa15accd91e0

GET http://localhost:3000/courses/{{COURSE_ID_REAL}} HTTP/1.1

### Request 5: Update Course
@COURSE_UPDATE_ID = 6981840d17e73adb5405a521

PUT http://localhost:3000/courses/{{COURSE_UPDATE_ID}} HTTP/1.1
content-type: application/json

{
    "name": "TPC Sawgrass",
    "location": "",
    "par": 72,
    "distance": 7555,
    "slope": 155  
}
